
# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [11]:
# Write your code here
import numpy as np
arr = np.array([10,20,30,40,50])
arr
print(f"Shape{np.shape(arr)}")
print(f"Dimensions:{np.ndim(arr)}")
print(f"Size:-{np.size(arr)}")
print(f"dtype:-{arr.dtype}")

Shape(5,)
Dimensions:1
Size:-5
dtype:-int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [12]:
# Write your code here
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.shape)

(2, 3)



# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [17]:
# Write your code here
arr = np.array([5,10,15,20,25])
print(arr[0])
print(arr[4])

5
25



# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [18]:
# Write your code here
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1,1])

50



# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [19]:
# Write your code here
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[2,2])

9



# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [20]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])

[20 30 40 50]



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [22]:
# Write your code here
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:5])

[1 2 3 4 5]



# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [28]:
# Write your code here
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr[0:])

[[1 2 3]
 [4 5 6]]



# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [36]:
# Write your code here
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:,:2])

[[10 20]
 [40 50]
 [70 80]]



# Q10. Boolean Indexing

## Problem Statement
Create the array:

```python
[5, 12, 18, 25, 30, 7]
```

Print only the values greater than 15.

## Sample Output
```python
[18 25 30]
```


In [38]:
# Write your code here
arr = np.array([5,18,12,25,30,7])
print(arr[arr>15])


[18 25 30]
